/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Winner = "draw" | "player_a" | "player_b";

export interface GameResults {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  player_a_id: string;
  player_b_id: string;
  winner: Winner;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface Players {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  player_id: string;
  player_name: string | null;
  score: Numeric;
}

export interface DB {
  game_results: GameResults;
  pgmigrations: Pgmigrations;
  players: Players;
}
